"""init 

Revision ID: ac640c9be8e2
Revises: edded56b4164
Create Date: 2023-12-20 20:24:30.919060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac640c9be8e2'
down_revision = 'edded56b4164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('director', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film')
    # ### end Alembic commands ###
